---
- name: include preinstall tasks
  include_tasks: preinstall.yml

# * preinstall - dependencies
- name: Install git
  ansible.builtin.package:
    name: git
    state: present
  when: install_git

# * install - clone git repos
- name: Clone git
  ansible.builtin.git:
    repo: "{{ uptime_kuma_git }}"
    dest: "{{ uptime_kuma_app }}"
    version: "{{ uptime_kuma_version }}"
    force: true
  become_user: "{{ uptime_kuma_user }}"
  become: true
  register: uptime_kuma_git_output

- name: install npm dependencies 
  community.general.npm:
    path: "{{ uptime_kuma_app }}"
    state: present
    production: true
  become_user: "{{ uptime_kuma_user }}"
  become: true
  when: uptime_kuma_git_output.changed
  notify: restart service

- name: run download-dist
  ansible.builtin.command:
    cmd: npm run download-dist
    chdir: "{{ uptime_kuma_app }}"
  become_user: "{{ uptime_kuma_user }}"
  become: true
  when: uptime_kuma_git_output.changed
  notify: restart service

- name: copy .env file
  ansible.builtin.template:
    src: env.j2
    dest: "{{ uptime_kuma_app }}/.env"
    owner: "{{ uptime_kuma_user }}"
    group: "{{ uptime_kuma_group }}"
  notify: restart service

# * postinstall - systemd
- name: copy systemd service file
  ansible.builtin.template:
    src: systemd.j2
    dest: /etc/systemd/system/uptime-kuma.service
    owner: root
    group: root
    mode: '0644'
  notify: restart service