---
# * preinstall - general
- name: ensure group exists
  ansible.builtin.group:
    name: "{{ uptime_kuma_group }}"
    system: true
    gid: "{{ uptime_kuma_group_gid | default(omit) }}"

- name: ensure user exists
  ansible.builtin.user:
    name: "{{ uptime_kuma_user }}"
    group: "{{ uptime_kuma_group }}"
    system: true
    create_home: true
    uid: "{{ uptime_kuma_user_uid | default(omit) }}"

- name: ensure directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    owner: "{{ uptime_kuma_user }}"
    group: "{{ uptime_kuma_group }}"
    state: directory
    follow: false
  with_items:
    - "{{ uptime_kuma_app }}"
    - "{{ uptime_kuma_data }}"
  