---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_distribution == 'Ubuntu'

  tasks:
    - name: "Include aacater.template"
      include_role:
        name: "aacater.template"
