---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

  tasks:
    - name: Install nodejs
      include_role:
        name: geerlingguy.nodejs

    - name: "Include aacater.uptime_kuma"
      include_role:
        name: "aacater.uptime_kuma"

  post_tasks:
    - name: Ensure uptime kuma is running.
      uri:
        url: http://127.0.0.1:3001/dashboard
        status_code:
          - 200
          - 302
      register: result
      until: result.status == 200
      retries: 60
      delay: 1