---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_distribution == 'Ubuntu'

  tasks:
    - name: "Include aacater.${REPO_NAME}"
      include_role:
        name: "aacater.${REPO_NAME}"

  # post_tasks:
  #   - name: Ensure app is running.
  #     uri:
  #       url: http://127.0.0.1:5601/login
  #       status_code: 200
  #     register: result
  #     until: result.status == 200
  #     retries: 60
  #     delay: 1
